### ISSUE TITLE
Kapitel benötigte Funktionen verbessern

### ISSUE THREAD

**Issue by daniw** [pren-t27/pren1#26]

**Comment by takuonen** [comment]
Was genau soll hier verbessert werden? 

Umschreiben? Total abändern?

**Comment by takuonen** [comment]
Der Weg zum Konzept sollte ja noch irgendwie erläutert werden. Wollen wir "Benötigte Funktionen" in "Vorbereitung Konzept" umbennenen?
Dann kann man Punkte wie das Brainstorming und Diskussionen am start noch einfügen. Diese Teile fehlen meiner Meinung nach noch.

**Comment by daniw** [comment]
Ich habe da mal was angefangen, bin aber noch nicht wirklich zufrieden damit. 

Der Weg ist halt folgender: 
Aufgabe -> extrahieren der notwendigen Funktionen -> Lösungsvarianten für jede Funktion -> Konzeptvarianten daraus -> definitives Konzept

**Comment by daniw** [comment]
Auflistungen in Text umwandeln.
