### ISSUE TITLE
Lösungskonzepte Reihenfolge Untertitel tauschen? 

### ISSUE THREAD

**Issue by daniw** [pren-t27/pren1#27]
Kommentar von Dozent zu Kurzbeschrieb Bodeneffekt Abschussvorrichtung: 

"Kommt ganz unangekündigt 
(Vorher bereits von dieser Variante schreiben!) 
oder 4.2.4 (Funktionsweise) vorziehen??"

Vorschlag für neue Reihenfolge: 
- Kurzbeschrieb
- Funktionsweise
- Morphologischer Kasten
- Vor- und Nachteile
- Risikoanalyse

Was haltet ihr davon?

**Comment by takuonen** [comment]
Ja wäre vielleicht nicht schlecht. Aber ist es wirklich so ein unterschied wenn die Funktionsweise vorgezogen wird? Diese Beschreibt ja sozusagen den morphologischen Kasten und die getätigte Auswahl.

Aber im Grunde wenn es zum besseren verständnis dient, kann man das auch gerne ändern.
