### ISSUE TITLE
Keine Gewichtung der Bewertungskriterien. Ok? 

### ISSUE THREAD

**Issue by daniw** [pren-t27/pren1#28]
Frage von Dozent zu Tabelle in Gegenüberstellung und Bewertung / Fazit

**Comment by takuonen** [comment]
Wir haben keine Spezielle gewichtung vorgenommen. Alles wird ja 1:1 übernommen.

Es war für uns einfach wichtig die Dauer und das Gewicht gering zu  halten oder?

**Comment by daniw** [comment]
Also können wir schreiben, dass wir bewusst keine Gewichtung vorgenommen haben, da alle Kriterien gleich wichtig sind?
