### ISSUE TITLE
Berechnungen: Abwägungen abschliessen

### ISSUE THREAD

**Issue by daniw** [pren-t27/pren1#30]
Bei Letztem Abschnitt im Kapitel Berechnungen

Kommentar des Dozenten: 

"Abwägung abschliessen: 
Was heisst es für das Konzept? 
-> Wenn bereits entschieden (sollte): beschreiben"

**Comment by mamaisse** [comment]
Ich werde mir da noch was überlegen!

**Comment by mamaisse** [comment]
Finito
