### ISSUE TITLE
Tests: Drehvorrichtung

### ISSUE THREAD

**Issue by daniw** [pren-t27/pren1#31]
Bemerkung Dozent: 

"Quantifizieren! Wie schnell. "

**Comment by mathda** [comment]
Was meinst du genau mit wie schnell? Wie lange der Turm braucht um sich zu drehen oder was?

**Comment by daniw** [comment]
Im Text steht "genügend schnell". Ich denke er meinte vor allem diese Stelle. Zudem gibt es die Stelle "ausreichend Kraft". 

Wir haben ja nicht wirklich Messungen gemacht da. Es war ja vor allem ein Test, ob es so überhaupt funktioniert.

**Comment by mathda** [comment]
Habe die Textstellen entsprechend angepasst.
