### ISSUE TITLE
Abgabe Dokumentation

### ISSUE THREAD

**Issue by daniw** [pren-t27/pren1#33]
Wer gibt die Dokumentation ab?

**Comment by takuonen** [comment]
Gute Frage : )

Bis wann machen wir die Änderungen? und Bis wann ist die definitive Abgabe?
Nicht am 9. Januar? Weiss nicht wieso aber aus irgend einem Grund habe ich dieses Datum im Kopf..

**Comment by daniw** [comment]
Die Abgabe ist am 9. Januar 12:00. 

Da müssen zwei Exemplare der Dokumentation und die CD mit der Dokumentation abgegeben und auf Ilias geladen werden. 

Da die eidesstattliche Erklärung von allen unterschrieben werden muss, wäre es ideal, wenn alle dann anwesend wären.

**Comment by daniw** [comment]
Ich kann die Dokumentation am Donnerstag Abend ausdrucken. 

Kann jemand die CD mit dem Anhang erstellen?

**Comment by daniw** [comment]
Dokumentation Drucken und binden: Daniel
CD mit Anhang brennen: Peter
