### ISSUE TITLE
Seitenränder

### ISSUE THREAD

**Issue by mathda** [pren-t27/pren1#36]
Die Seitenränder sollten doch noch etwas kleiner gemacht werden...?!?

**Comment by takuonen** [comment]
Finde das Layout ansich so eigentlich nicht schlecht. Wie würdes du es am liebsten haben?

Ist ja rein geschmackssache vom DeAngelis oder nicht?

**Comment by daniw** [comment]
Für gewisse Tabellen wäre es nicht schlecht, wenn der Text etwas breiter wäre. 

Erstelle bis heute Abend mal einen Vorschlag.
