### ISSUE TITLE
Dokument Brainstorming

### ISSUE THREAD

**Issue by daniw** [pren-t27/pren1#37]
Im Kapitel "Lösungskonzepte" wird auf das Dokument "Brainstorming" verwiesen. 

Wo ist das? 

Müsste das in den Anhang?

**Comment by takuonen** [comment]
Ist das jetzt in Ordnung? Haben das ja gestern noch angeschaut?

**Comment by daniw** [comment]
Wo ist denn das Dokument? 

Das pdf davon müsste in den Ordner appendix. 

Ausserdem müsste es in appendix.tex ergänzt werden.
